version: "3"
services:
  app:  
    image: node:12-alpine
    container_name: pikabot-chat
    restart: unless-stopped
    
    volumes:
      - ./:/myapp
    
    working_dir: /myapp
    
    environment:
      NODE_ENV: development
    
    ports:
      - 5000:5000
    
    command: >
        sh -c "npm ci && npm run dev"
    #command: sh -c "npm install -g pm2 && npm install && pm2-runtime index.js --watch"
    #command: npm run start              
    #command: npm run dev